version: "3.9"

services:
  portfolio-app:
    image: '<Provide the image name here>'
    container_name: econtractx-service
    ports:
      - "8080:8080"
#    Update environment variables as needed
    environment:
      - JWT_SECRET=
      - API_POSTS_URL=https
      - SPRING_DATA_MONGODB_URI=
      - SPRING_SECURITY_USER_NAME=
      - SPRING_SECURITY_USER_PASSWORD=
    networks:
      - econtractx-network
    restart: unless-stopped
networks:
  econtractx-network:
    driver: bridge



